language: cpp
compiler:
    - clang
    - gcc
sudo: required
before_install:
    - sudo apt-get update --option Acquire::Retries=100 --option Acquire::http::Timeout="60"
    - perl .travis/apt.pl
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
env:
    - NOTHING=1
    - FULLDEBUG=1
    - TILES=1
    - TILES=1 FULLDEBUG=1
    - WEBTILES=1
    - WEBTILES=1 FULLDEBUG=1
    - USE_DGAMELAUNCH=1 EXTERNAL_DEFINES=-UTOURNEY
    - USE_DGAMELAUNCH=1 WEBTILES=1 EXTERNAL_DEFINES=-UTOURNEY
    - TILES=1 BUILD_ALL=1
    - WEBTILES=1 BUILD_ALL=1
git:
    submodules: false
install: perl .travis/deps.pl
script: perl .travis/build.pl
notifications:
    email:
        on_success: change
        on_failure: always
    irc:
        channels: "chat.freenode.net##crawl-forks"
        on_success: change
        on_failure: always
        use_notice: true
        template:
            - "%{message} (%{branch} - %{commit} #%{build_number} : %{author}): %{build_url}"
