language: cpp
compiler:
#    - clang
    - gcc
before_install:
    - perl .travis/apt.pl
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
env:
#    - NOTHING=1
#    - FULLDEBUG=1
#    - TILES=1
#    - TILES=1 FULLDEBUG=1
#    - WEBTILES=1
    - WEBTILES=1 FULLDEBUG=1
#    - USE_DGAMELAUNCH=1 EXTERNAL_DEFINES=-UTOURNEY
#    - USE_DGAMELAUNCH=1 WEBTILES=1 EXTERNAL_DEFINES=-UTOURNEY
#    - TILES=1 BUILD_ALL=1
#    - WEBTILES=1 BUILD_ALL=1
    - MONSTER=1
git:
    submodules: false
install: perl .travis/deps.pl
script: perl .travis/build.pl
notifications:
    irc:
        channels: "chat.freenode.net##circusfork"
        on_success: change
        on_failure: change
        use_notice: true
        template:
            - "%{message} (%{branch} - %{commit} #%{build_number} : %{author}): %{build_url}"
#    email:
#        on_success: change
#        on_failure: always
#        recipients:
#          - crawl-ref-commits@lists.sourceforge.net
sudo: required
