#pragma once

enum potion_type
{
    POT_CURING,
    POT_HEAL_WOUNDS,
    POT_HASTE,
    POT_MIGHT,
    POT_BRILLIANCE,
    POT_AGILITY,
    POT_FLIGHT,
    POT_CANCELLATION,
    POT_AMBROSIA,
    POT_INVISIBILITY,
    POT_DEGENERATION,
    POT_EXPERIENCE,
    POT_MAGIC,
    POT_BERSERK_RAGE,
    POT_MUTATION,
    POT_RESISTANCE,
    POT_BLOOD,
    POT_LIGNIFY,
    NUM_POTIONS
};
