#pragma once

enum timed_effect_type
{
    TIMER_CORPSES,
    TIMER_HELL_EFFECTS,
    TIMER_CONTAM,
    TIMER_GOD_EFFECTS,
    TIMER_FOOD_ROT,
    TIMER_PRACTICE,
    TIMER_LABYRINTH,
    TIMER_ABYSS_SPEED,
    TIMER_JIYVA,
    TIMER_EVOLUTION,
    NUM_TIMERS,
};
