name: Build

on:
  push: {}
  pull_request: {}
  release:
    types:
      - created

jobs:
  linting:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unbrace
        run: util/unbrace -n
        working-directory: crawl-ref/source
      - name: Checkwhite
        run: util/checkwhite -n
        working-directory: crawl-ref/source
  build_linux:
    name: Linux ${{ matrix.compiler }} ${{ matrix.build_opts }} ${{ matrix.debug }} tag_upgrade=${{ matrix.tag_upgrade }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
        build_opts:
          - ""
          - WEBTILES=1
          - WEBTILES=1 USE_DGAMELAUNCH=1
          - TILES=1
        debug:
          - ""
          - FULLDEBUG=1
        tag_upgrade:
          - false
        exclude:
          # Limit Clang jobs:
          # 1. Only build fulldebug
          - compiler: clang
            debug: ""
          # 2. Skip webtiles builds (all webtiles servers use GCC)
          - compiler: clang
            build_opts: WEBTILES=1 USE_DGAMELAUNCH=1
          - compiler: clang
            build_opts: WEBTILES=1
        include:
          - compiler: gcc
            build_opts: ""
            debug: FULLDEBUG=1
            tag_upgrade: true
          - compiler: gcc
            build_opts: WEBTILES=1 USE_DGAMELAUNCH=1
            debug: FULLDEBUG=1
            tag_upgrade: true
          - compiler: gcc
            build_opts: TILES=1
            debug: FULLDEBUG=1
            tag_upgrade: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Install dependencies
        run: ./deps.py --compiler ${{ matrix.compiler }} --build-opts "${{ matrix.build_opts }}"
        working-directory: .github/workflows
      - name: Add ccache to PATH
        run: echo "::add-path::/usr/lib/ccache"
      - name: Cache compilation
        uses: actions/cache@v1
        with:
          path: $HOME/.ccache
          key: ccache-linux-${{ matrix.compiler }}-${{ matrix.tag_upgrade }}-${{ matrix.build_opts }}-${{ matrix.debug }}
          restore-keys: |
            ccache-linux-${{ matrix.compiler }}-${{ matrix.tag_upgrade }}-${{ matrix.build_opts }}-${{ matrix.debug }}
            ccache-linux-${{ matrix.compiler }}-${{ matrix.tag_upgrade }}-${{ matrix.build_opts }}-${{ matrix.debug }}
            ccache-linux-${{ matrix.compiler }}-${{ matrix.tag_upgrade }}-${{ matrix.build_opts }}-
            ccache-linux-${{ matrix.compiler }}-${{ matrix.tag_upgrade }}-
            ccache-linux-${{ matrix.compiler }}-
      # ccache uses ~110mb to store the output from a single crawl compile
      # (including submodules) (when compressed)
      - name: Configure ccache
        run: |
          mkdir -p ~/.ccache
          cat >~/.ccache/ccache.conf <<EOF
          compression = true
          compression_level = 9
          log_file = /tmp/ccache.log
          max_size = 150M
          EOF
      - name: Display ccache configuration
        run: |
          ccache -s
          ls -l /usr/lib/ccache
      - name: Run tag upgrade scripts
        if: matrix.tag_upgrade == true
        run: |
          if ! grep -q '#define TAG_MAJOR_VERSION 34' tag-version.h ; then
            echo "::error ::CI job for TAG_MAJOR_VERSION testing needs to be updated for new major tag"
            exit 1
          fi
          sed -i'' -e 's/^#define TAG_MAJOR_VERSION 34$/#define TAG_MAJOR_VERSION 35/' tag-version.h
          util/tag-major-upgrade -t 35
          util/tag-35-upgrade.py
        working-directory: crawl-ref/source
      - run: make -j$(nproc) ${{ matrix.build_opts }} ${{ matrix.debug }}
        working-directory: crawl-ref/source
      - name: Print ccache stats
        run: ccache -s

  build_macos:
    name: macOS ${{ matrix.build_type }}
    runs-on: macos-latest
    strategy:
      matrix:
        build_type:
          - tiles
          - console
        build_opts:
          - ""
          - TILES=y
        exclude:
          - build_type: tiles
            build_opts: ""
          - build_type: console
            build_opts: TILES=y
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install Dependencies
        run: |
          brew install ccache
          sudo pip3 install PyYAML
      - name: Add ccache to PATH
        run: echo "::add-path::/usr/local/opt/ccache/libexec"
      - name: Cache compilation
        uses: actions/cache@v1
        with:
          path: $HOME/.ccache
          key: ccache-macos-clang-${{ matrix.build_type }}
          restore-keys: |
            ccache-macos-clang-${{ matrix.build_type }}
            ccache-macos-clang
      # ccache uses ~110mb to store the output from a single crawl compile
      # (including submodules) (when compressed)
      - name: Configure ccache
        run: |
          mkdir -p ~/.ccache
          cat >~/.ccache/ccache.conf <<EOF
          compression = true
          compression_level = 9
          log_file = /tmp/ccache.log
          max_size = 150M
          EOF
      - name: Display ccache configuration
        run: |
          ccache -s
          ls -l /usr/local/opt/ccache/libexec
      - run: make -j$(sysctl -n hw.ncpu) mac-app-${{ matrix.build_type }} ${{matrix.build_opts }}
        working-directory: crawl-ref/source
      - name: Print ccache stats
        run: ccache -s
      - name: Add build to release
        if: github.event.release.tag_name != null
        # Go back to the upstream action (svenstaro/upload-release-action) once this PR merges:
        # https://github.com/svenstaro/upload-release-action/pull/13
        uses: alexjurkiewicz/upload-release-action@6408db765e9a0413e6c5b8231ecd3eb45352cc99
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: crawl-ref/source/mac-app-zips/latest.zip
          asset_name: dcss-$tag-macos-${{ matrix.build_type}}.zip

  build_mingw64_crosscompile:
    name: mingw64 ${{ matrix.build_type }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type:
          - tiles
          - console
          - installer
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules (for crosscompile)
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install dependencies
        run: ./deps.py --crosscompile
        working-directory: .github/workflows
      - name: Add ccache to PATH
        run: echo "::add-path::/usr/lib/ccache"
      - name: Cache compilation
        uses: actions/cache@v1
        with:
          path: $HOME/.ccache
          key: ccache-mingw64-${{ matrix.build_type }}
          restore-keys: |
            ccache-mingw64-${{ matrix.build_type }}
            ccache-mingw64
      # ccache uses ~110mb to store the output from a single crawl compile
      # (including submodules) (when compressed)
      - name: Configure ccache
        run: |
          mkdir -p ~/.ccache
          cat >~/.ccache/ccache.conf <<EOF
          compression = true
          compression_level = 9
          log_file = /tmp/ccache.log
          max_size = 150M
          EOF
      - name: Display ccache configuration
        run: |
          ccache -s
          ls -l /usr/lib/ccache
      - run: make -j$(nproc) CROSSHOST=i686-w64-mingw32 package-windows-${{ matrix.build_type }}
        working-directory: crawl-ref/source
      - name: Print ccache stats
        run: ccache -s
      # The zip & installer targets create different sorts of names, so we need
      # a little shell script magic here.
      - name: Determine release file names
        if: github.event.release.tag_name != null
        id: release-names
        run: |
          if [[ ${{ matrix.build_type }} != installer ]] ; then
            source='crawl-ref/source/stone_soup-latest-${{ matrix.build_type}}-win32.zip'
            dest='dcss-$tag-win32-${{ matrix.build_type}}.zip'
          else
            source='crawl-ref/source/stone_soup-latest-win32-installer.exe'
            dest='dcss-$tag-win32-installer.exe'
          fi
          echo "::set-output name=source::$source"
          echo "::set-output name=dest::$dest"
      - name: Add build to release
        if: github.event.release.tag_name != null
        # Go back to the upstream action (svenstaro/upload-release-action) once this PR merges:
        # https://github.com/svenstaro/upload-release-action/pull/13
        uses: alexjurkiewicz/upload-release-action@6408db765e9a0413e6c5b8231ecd3eb45352cc99
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ${{ steps.release-names.outputs.source }}
          asset_name: ${{ steps.release-names.outputs.dest }}

  codecov_catch2:
    name: Catch2 (GCC/Linux) + Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Install dependencies
        run: ./deps.py --coverage
        working-directory: .github/workflows
      - name: Add ccache to PATH
        run: echo "::add-path::/usr/lib/ccache"
      - name: Cache compilation
        uses: actions/cache@v1
        with:
          path: /home/runner/.ccache
          key: ccache-catch2
          restore-keys: |
            ccache-catch2
      # ccache uses ~110mb to store the output from a single crawl compile
      # (including submodules) (when compressed)
      - name: Configure ccache
        run: |
          mkdir -p ~/.ccache
          cat >~/.ccache/ccache.conf <<EOF
          compression = true
          compression_level = 9
          log_file = /tmp/ccache.log
          max_size = 150M
          EOF
      - name: Display ccache configuration
        run: |
          ccache -s
          ls -l /usr/lib/ccache
      - run: make -j$(nproc) catch2-tests
        working-directory: crawl-ref/source
      - name: Print ccache stats
        run: ccache -s
      - name: Generate LCOV data
        working-directory: crawl-ref/source
        run: >
          lcov
          --capture
          --directory .
          --output-file ../../coverage.info
          --ignore-errors source
          --rc lcov_branch_coverage=1
      - name: Remove unimportant files from coverage
        working-directory: crawl-ref/source
        run: |
          mv ../../coverage.info ../../coverage.info.old
          lcov --remove ../../coverage.info.old \
            'crawl-ref/source/catch2-tests/*' \
            --rc lcov_branch_coverage=1 \
            -o ../../coverage.info
      - name: Send coverage data to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.info
          flags: catch2
          fail_ci_if_error: false

  webserver:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies (py2)
      if: matrix.python-version == 2.7
      working-directory: crawl-ref/source/webserver
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.py2.txt
    - name: Install dependencies (py3)
      if: matrix.python-version != 2.7
      working-directory: crawl-ref/source/webserver
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.py3.txt
    - name: Lint (flake8)
      if: matrix.python-version != 2.7
      working-directory: crawl-ref/source/webserver
      run: make lint
    - name: Import Sorting (isort)
      working-directory: crawl-ref/source/webserver
      run: make format
    - name: Unit Tests (pytest)
      working-directory: crawl-ref/source/webserver
      run: pytest
