name: Dungeon Crawl Stone Soup - compile

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
      working-directory: crawl-ref/source
